name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Convert Markdown into HTML and PDF
        uses: KoharaKazuya/marp-cli-action@v4

      - name: Uploade artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

# Please update URL if you want to use custom domain
#URL: https://${{ github.event.repository.owner.name }}.github.io/${{ github.event.repository.name }}
#BRANCH: gh-pages
#FOLDER: dist
