name: Manuell starten

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Umgebung'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Zeige Eingabe
        run: echo "Ausgewählte Umgebung: ${{ github.event.inputs.environment }}"
